application: answr-it
version: 27
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /answr
  script: main.py

- url: /q
  script: main.py

- url: /populate
  login: admin
  script: populate.py

- url: /temp_populate
  login: admin
  script: temp.py

- url: /twitterbot
  login: admin
  script: twitterbot.py

- url: /_ah/xmpp/message/chat/
  script: xmpp.py

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

inbound_services:
- xmpp_message
